---
title: "project_part_2"
author: "Dwiref Oza"
date: "12/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(GGally)
library(ggplot2)
library(corrplot)
library(psych)
library(caret)
library(rpart)
library(randomForest)
library(nnet)
library(e1071)
library(ROCR)
library(CORElearn)
library(lasso2)
```

```{r}
# read in data
filename <- 'diabetic_data.csv'
data <- read.table(filename, sep = ",", header = T, na.strings = "?")
head(data)

#load(file = "data2.rdata")
```

```{r}
# PREPROCESSING, CLEANING

# remove unnecessary columns patient/encounter IDs, weight(97% missing), drugs
data <- select(data, -encounter_id, -patient_nbr, -weight,-(25:41),-(43:47))
data$race[is.na(data$race)] <- "Other"
```

```{r}
# FEATURE EXTRACTION

data2 <- data

data2$diag_1 <- as.numeric(levels(data2$diag_1)[data2$diag_1])
data2$diag_2 <- as.numeric(levels(data2$diag_2)[data2$diag_2])
data2$diag_3 <- as.numeric(levels(data2$diag_3)[data2$diag_3])

# diagnosis1
data2$diagnosis_group <- factor( rep("other",nrow(data2)),ordered = F, 
                                 levels = c("circulatory","respiratory","Digestive","Diabetes","Injury",
                                            "Musculoskeletal","Genitourinary","Neoplasms","other"))
data2$diagnosis_group[data2$diag_1>=390 & data2$diag_1 <= 459 | data2$diag_1==785] <- "circulatory"
data2$diagnosis_group[data2$diag_1>=460 & data2$diag_1 <= 519 | data2$diag_1==786] <- "respiratory"
data2$diagnosis_group[data2$diag_1>=520 & data2$diag_1 <= 579 | data2$diag_1==787] <- "Digestive"
data2$diagnosis_group[data2$diag_1>=250 & data2$diag_1 < 251] <- "Diabetes"
data2$diagnosis_group[data2$diag_1>800 & data2$diag_1 <= 999] <- "Injury"
data2$diagnosis_group[data2$diag_1>=710 & data2$diag_1 <= 739] <- "Musculoskeletal"
data2$diagnosis_group[data2$diag_1>=580 & data2$diag_1 <= 629 | data2$diag_1==788] <- "Genitourinary"
data2$diagnosis_group[data2$diag_1>=140 & data2$diag_1 <= 239 | data2$diag_1>=790 & 
                        data2$diag_1 <= 799 | data2$diag_1==780 | data2$diag_1>=240 & data2$diag_1 < 250 |
                        data2$diag_1>=251 & data2$diag_1 <= 279 | data2$diag_1>=680 & data2$diag_1 <= 709 |
                        data2$diag_1>=001 & data2$diag_1 <= 139 | data2$diag_1==781 |
                      data2$diag_1==782 | data2$diag_1==784] <- "Neoplasms"

# diagnosis_2
data2$diagnosis_2 <- factor( rep("other",nrow(data2)),ordered = F, 
                                 levels = c("circulatory","respiratory","Digestive","Diabetes","Injury",
                                            "Musculoskeletal","Genitourinary","Neoplasms","other"))
data2$diagnosis_2[data2$diag_2>=390 & data2$diag_2 <= 459 | data2$diag_2==785] <- "circulatory"
data2$diagnosis_2[data2$diag_2>=460 & data2$diag_2 <= 519 | data2$diag_2==786] <- "respiratory"
data2$diagnosis_2[data2$diag_2>=520 & data2$diag_2 <= 579 | data2$diag_2==787] <- "Digestive"
data2$diagnosis_2[data2$diag_2>=250 & data2$diag_2 < 251] <- "Diabetes"
data2$diagnosis_2[data2$diag_2>800 & data2$diag_2 <= 999] <- "Injury"
data2$diagnosis_2[data2$diag_2>=710 & data2$diag_2 <= 739] <- "Musculoskeletal"
data2$diagnosis_2[data2$diag_2>=580 & data2$diag_2 <= 629 | data2$diag_2==788] <- "Genitourinary"
data2$diagnosis_2[data2$diag_2>=140 & data2$diag_2 <= 239 | data2$diag_2>=790 & 
                        data2$diag_2 <= 799 | data2$diag_2==780 | data2$diag_2>=240 & data2$diag_2 < 250 |
                        data2$diag_2>=251 & data2$diag_2 <= 279 | data2$diag_2>=680 & data2$diag_2 <= 709 |
                        data2$diag_2>=001 & data2$diag_2 <= 139 | data2$diag_2==781 |
                        data2$diag_2==782 | data2$diag_2==784] <- "Neoplasms"

# diagnosis_3
data2$diagnosis_3 <- factor( rep("other",nrow(data2)),ordered = F, 
                                 levels = c("circulatory","respiratory","Digestive","Diabetes","Injury",
                                            "Musculoskeletal","Genitourinary","Neoplasms","other"))
data2$diagnosis_3[data2$diag_3>=390 & data2$diag_3 <= 459 | data2$diag_3==785] <- "circulatory"
data2$diagnosis_3[data2$diag_3>=460 & data2$diag_3 <= 519 | data2$diag_3==786] <- "respiratory"
data2$diagnosis_3[data2$diag_3>=520 & data2$diag_3 <= 579 | data2$diag_3==787] <- "Digestive"
data2$diagnosis_3[data2$diag_3>=250 & data2$diag_3 < 251] <- "Diabetes"
data2$diagnosis_3[data2$diag_3>800 & data2$diag_3 <= 999] <- "Injury"
data2$diagnosis_3[data2$diag_3>=710 & data2$diag_3 <= 739] <- "Musculoskeletal"
data2$diagnosis_3[data2$diag_3>=580 & data2$diag_3 <= 629 | data2$diag_3==788] <- "Genitourinary"
data2$diagnosis_3[data2$diag_3>=140 & data2$diag_3 <= 239 | data2$diag_3>=790 & 
                        data2$diag_3 <= 799 | data2$diag_3==780 | data2$diag_3>=240 & data2$diag_3 < 250 |
                        data2$diag_3>=251 & data2$diag_3 <= 279 | data2$diag_3>=680 & data2$diag_3 <= 709 |
                        data2$diag_3>=001 & data2$diag_3 <= 139 | data2$diag_3==781 |
                        data2$diag_3==782 | data2$diag_3==784] <- "Neoplasms"
# admission_source
data2$admission_source <- factor( rep("other",nrow(data2)),ordered = F, 
                             levels = c("clinic_referral", "emergency","other"))
data2$admission_source[data2$admission_source_id==c(1,2,3)]<- "clinic_referral"
data2$admission_source[data2$admission_source_id==7]<- "emergency"

# discharged_to
data2$discharged_to <- factor( rep("transferred",nrow(data2)),ordered = F, 
                                  levels = c("home", "transferred","left_AMA"))
data2$discharged_to[data2$discharge_disposition_id==c(1,6,8)]<- "home"
data2$discharged_to[data2$discharge_disposition_id==7]<- "left_AMA"

data2 <- select(data2, -diag_1, -diag_2, -diag_3, -admission_type_id, -discharge_disposition_id)
data2 <- select(data2, -medical_specialty)
data2 <- rename(data2, diag1 = diagnosis_group, diag2=diagnosis_2, diag3 = diagnosis_3)

# payer_code
data2$payer_code2 <- factor( rep("other",nrow(data2)),ordered = F, 
                               levels = c("other", "self_pay"))
data2$payer_code2[data2$payer_code=="SP"]<- "self_pay"
data2 <- select(data2, -payer_code)
data2 <- select(data2, -admission_source_id)
data2 <- rename(data2, payer_code=payer_code2)
```

```{r}
# SPLIT DATA INTO TRAINING AND TESTING SET

set.seed(123)
inTrain <- createDataPartition(y = data2$readmitted, p = .66,list = FALSE)
train <- data2[ inTrain,]
test <- data2[-inTrain,]
nrow(train) # 67167
nrow(test) # 3459
```

```{r}
# SUPPORT VECTOR MACHINES
library(parallelSVM)
SVMmodel <- parallelSVM(readmitted ~ age+discharged_to+time_in_hospital+
                  num_lab_procedures+num_procedures+num_medications+number_outpatient+
                  number_emergency+number_inpatient+number_diagnoses+
                  insulin+change+diabetesMed+diag1+diag2+diag3+A1Cresult,
                data=train, kernel = "linear")
                  #kernel = "rbf", gamma = 0.1, cost = 1)
print(SVMmodel)
summary(SVMmodel)
x <- select(test, -readmitted)
y <- select(test, readmitted)
pred <- predict(SVMmodel, x)
test$pred_readmit <- pred
prop.table(table(test$readmitted, test$pred_readmit),1)
confusionMatrix(test$pred_readmit, test$readmitted)

# visualize (classes by color, SV by crosses):
plot(cmdscale(dist(x)),
     col = as.integer(y),
     pch = c("o","+")[1:(nrow(data2)) %in% SVMmodel$index + 1])

```


